import os
import sys

# Prompt for camera source before importing modules that read the config
if "SA_RTSP_URL" not in os.environ:
    print("\n" + "="*40)
    print("🎥 CAMERA SELECTION")
    print("="*40)
    print("If you are using DroidCam (USB), it is usually index 1 or 2.")
    print("If you are using DroidCam (Wi-Fi), enter the URL (e.g., http://192.168.1.5:4747/video)")
    print("Available USB indexes found earlier: [0, 1, 2, 3, 5, 6]")
    print("="*40)
    cam = input("Enter camera index or URL (press Enter to try index 1 first): ").strip()
    if cam:
        os.environ["SA_RTSP_URL"] = cam
    else:
        # Default to 1 because 0 is Iriun Webcam on this machine
        os.environ["SA_RTSP_URL"] = "1"

import time
import cv2
import numpy as np
import threading
import requests
from core.tracking import VideoStreamBuffer, Tracker
from core.analytics import AnalyticsOrchestrator
from core.config import ENTRY_EXIT_LINE, OPERATIONAL_ZONES, PROMOTIONAL_DISPLAYS, INTERACTIVE_SHELVES
from database.store_db import db
from core.replenishment_engine import ReplenishmentEngine

from core.visualization import (
    detect_staff_heuristic, draw_bounding_box_with_label,
    draw_queue_metrics, overlay_heatmap_pip, overlay_zones,
    draw_trajectory, draw_staff_interaction
)
from collections import defaultdict
from core.analytics import is_point_in_polygon

drawing_poly = []
new_zones = {}

def mouse_callback(event, x, y, flags, param):
    global drawing_poly
    if event == cv2.EVENT_LBUTTONDOWN:
        drawing_poly.append((x, y))

def setup_zones_interactive(frame):
    global drawing_poly, new_zones
    cv2.namedWindow("Setup Zones")
    cv2.setMouseCallback("Setup Zones", mouse_callback)
    
    print("\n--- ZONE SETUP ---")
    print("Click to draw points for a polygon. Press 'c' to close the polygon and name it. Press 'd' to finish setup.")
    
    while True:
        display = frame.copy()
        
        display = overlay_zones(display, OPERATIONAL_ZONES)
        display = overlay_zones(display, INTERACTIVE_SHELVES)
        display = overlay_zones(display, new_zones)
        
        if len(drawing_poly) > 0:
            pts = np.array(drawing_poly, np.int32).reshape((-1, 1, 2))
            cv2.polylines(display, [pts], isClosed=False, color=(0, 255, 0), thickness=2)
            for p in drawing_poly:
                cv2.circle(display, p, 4, (0, 0, 255), -1)
                
        cv2.putText(display, "Setup Mode: Draw Zones. 'c' to save, 'd' to start.", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 255), 2)
        cv2.imshow("Setup Zones", display)
        
        key = cv2.waitKey(1) & 0xFF
        if key == ord('c') and len(drawing_poly) > 2:
            print("\nZone drawn! Go to terminal and enter a name for this zone:")
            name = input("Zone Name (e.g. Checkout): ").strip()
            if name:
                new_zones[name] = drawing_poly.copy()
            drawing_poly = []
            print("Zone saved! Draw another or press 'd' to finish.")
        elif key == ord('d'):
            break
            
    cv2.destroyWindow("Setup Zones")
    OPERATIONAL_ZONES.update(new_zones)
    print("Zone Setup Complete.\n")

def display_insights():
    """Background thread to occasionally print business insights generated by the DB."""
    while True:
        time.sleep(60) # Generate insights every 60 seconds
        insights = db.generate_insights()
        if insights:
            print("\n" + "="*40)
            print("💡 BUSINESS INSIGHTS GENERATOR")
            print("="*40)
            for insight in insights:
                print(insight)
            print("="*40 + "\n")

def main():
    print("[System] Initializing Refactored Shopper Analytics Engine...")
    
    stream = VideoStreamBuffer(use_gstreamer=False)
    tracker = Tracker()
    analytics = AnalyticsOrchestrator()
    
    track_history = defaultdict(list)
    track_dwell_state = {} # t_id -> {"zone": str, "entry_time": float}
    MAX_HISTORY = 60 # Remember path for ~2 seconds
    last_queue_update = 0

    
    # Start insight generator thread
    insight_thread = threading.Thread(target=display_insights, daemon=True)
    insight_thread.start()
    
    # Start inventory replenishment engine
    replenishment_engine = ReplenishmentEngine(store_id="STORE_001")
    replenishment_engine.start()
    
    stream.start()
    time.sleep(2)
    
    # Interactive Setup
    first_frame = stream.get_latest_frame()
    if first_frame is not None:
        setup_zones_interactive(first_frame)
        
    print("[System] Pipeline running. Press Ctrl+C to stop.")
    
    try:
        while True:
            frame = stream.get_latest_frame()
            if frame is None:
                time.sleep(0.01)
                continue
                
            # 1. Ingestion & Tracking Phase
            tracks = tracker.infer_and_track(frame)
            
            # Pre-calculate staff for analytics
            staff_ids = set()
            for t in tracks:
                if detect_staff_heuristic(frame, t['bbox']):
                    staff_ids.add(t['track_id'])
            
            # 2. Analytics Extraction Phase
            analytics.process(tracks, staff_ids)
            
            # 3. Visualization Pipeline - Real-time tracking overlay
            active_shoppers = 0
            staff_count = 0
            checkout_shoppers = 0
            
            # Draw defined zones
            frame = overlay_zones(frame, OPERATIONAL_ZONES)
            frame = overlay_zones(frame, INTERACTIVE_SHELVES)
            
            for t in tracks:
                bbox = t['bbox']
                centroid = t['centroid']
                t_id = t['track_id']
                age = t.get('age', 'N/A')
                gender = t.get('gender', 'N/A')
                
                # Update track history for trajectory drawing
                track_history[t_id].append(centroid)
                if len(track_history[t_id]) > MAX_HISTORY:
                    track_history[t_id].pop(0)
                
                is_staff = t_id in staff_ids
                if is_staff:
                    staff_count += 1
                    label = f"ID: {t_id} Staff"
                else:
                    active_shoppers += 1
                    
                    # Determine Zone Activity
                    current_zone = "Active Shopper"
                    for zone_name, poly in OPERATIONAL_ZONES.items():
                        if is_point_in_polygon(centroid, poly):
                            current_zone = f"Browsing {zone_name}"
                            if "checkout" in zone_name.lower():
                                current_zone = "Waiting at Checkout"
                            break
                            
                    # Calculate live dwell time
                    current_time = time.time()
                    if t_id not in track_dwell_state or track_dwell_state[t_id]["zone"] != current_zone:
                        track_dwell_state[t_id] = {"zone": current_zone, "entry_time": current_time}
                        
                    dwell_seconds = int(current_time - track_dwell_state[t_id]["entry_time"])
                    mins, secs = divmod(dwell_seconds, 60)
                    dwell_str = f"{mins:02d}:{secs:02d}"
                    
                    gen_abbr = gender[0] if gender != 'N/A' else '?'
                    label = f"ID: {t_id} [{age}|{gen_abbr}] [{dwell_str}]"
                    
                    if "Checkout" in current_zone:
                        draw_queue_metrics(frame, bbox, dwell_str)
                        checkout_shoppers += 1
                        
                    # Draw trajectory path for shoppers
                    draw_trajectory(frame, track_history[t_id], color=(0, 255, 0))
                
                draw_bounding_box_with_label(frame, bbox, label, is_staff)

            # Draw staff interactions
            for pair, start_time in analytics.staff_service.interaction_states.items():
                s_id, sh_id = pair
                s_track = next((t for t in tracks if t['track_id'] == s_id), None)
                sh_track = next((t for t in tracks if t['track_id'] == sh_id), None)
                if s_track and sh_track:
                    draw_staff_interaction(frame, s_track['centroid'], sh_track['centroid'])

            # Cleanup old track histories and dwell states
            active_ids = {t['track_id'] for t in tracks}
            for t_id in list(track_history.keys()):
                if t_id not in active_ids:
                    del track_history[t_id]
            for t_id in list(track_dwell_state.keys()):
                if t_id not in active_ids:
                    del track_dwell_state[t_id]

            # PIP Heatmap Overlay
            heatmap_img = analytics.get_heatmap()
            frame = overlay_heatmap_pip(frame, heatmap_img, active_shoppers, staff_count)

            if time.time() - last_queue_update > 2.0:
                try:
                    requests.post("http://localhost:8000/api/queue/update", json={"queue_persons": checkout_shoppers}, timeout=0.1)
                except Exception:
                    pass
                last_queue_update = time.time()

            cv2.imshow("Live MVP Feed", frame)
            
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break
            
            time.sleep(0.03)

    except KeyboardInterrupt:
        print("\n[System] Shutdown signal received.")
    finally:
        print("[System] Cleaning up resources...")
        stream.stop()
        replenishment_engine.stop()
        db.shutdown()
        cv2.destroyAllWindows()
        print("[System] Shutdown complete.")

if __name__ == "__main__":
    main()
