import time
import sys
import cv2
import numpy as np
import threading

from core.tracking import VideoStreamBuffer, Tracker
from core.analytics import AnalyticsOrchestrator
from core.config import ENTRY_EXIT_LINE, OPERATIONAL_ZONES, PROMOTIONAL_DISPLAYS
from database.store_db import db

def display_insights():
    """Background thread to occasionally print business insights generated by the DB."""
    while True:
        time.sleep(60) # Generate insights every 60 seconds
        insights = db.generate_insights()
        if insights:
            print("\n" + "="*40)
            print("💡 BUSINESS INSIGHTS GENERATOR")
            print("="*40)
            for insight in insights:
                print(insight)
            print("="*40 + "\n")

def main():
    print("[System] Initializing Refactored Shopper Analytics Engine...")
    
    stream = VideoStreamBuffer(use_gstreamer=False)
    tracker = Tracker()
    analytics = AnalyticsOrchestrator()
    
    # Start insight generator thread
    insight_thread = threading.Thread(target=display_insights, daemon=True)
    insight_thread.start()
    
    stream.start()
    time.sleep(2)
    print("[System] Pipeline running. Press Ctrl+C to stop.")
    
    try:
        while True:
            frame = stream.get_latest_frame()
            if frame is None:
                time.sleep(0.01)
                continue
                
            # 1. Ingestion & Tracking Phase
            tracks = tracker.infer_and_track(frame)
            
            # 2. Analytics Extraction Phase
            analytics.process(tracks)
            
            # 3. Visualization Pipeline - Real-time tracking overlay only
            for t in tracks:
                x1, y1, x2, y2 = map(int, t['bbox'])
                cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 255), 2)
                cv2.putText(frame, f"ID: {t['track_id']}", (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 255), 2)

            cv2.imshow("Live MVP Feed", frame)
            cv2.imshow("Thermal Heatmap", analytics.get_heatmap())
            
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break
            
            time.sleep(0.03)

    except KeyboardInterrupt:
        print("\n[System] Shutdown signal received.")
    finally:
        print("[System] Cleaning up resources...")
        stream.stop()
        db.shutdown()
        cv2.destroyAllWindows()
        print("[System] Shutdown complete.")

if __name__ == "__main__":
    main()
